config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  devise_for :users
  resources :categories
  resources :lunch_orders, only: [:index, :show]
  resources :customer_orders do
    resources :customer_order_items
    member do
      post :cancel
    end
  end
  resources :menus
  resources :product_imports do
    collection { post :import }
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud

    @user = user || User.new

    case
    when user.admin?
      can :manage, :all
    when user.restaurant?
      restaurant_permissions
    when user.customer?
      customer_permissions
    else
      cannot :manage, :all
    end
  end

  private
    def restaurant_permissions
      can :crud, Product, user_id: @user.id
      can :read, CustomerOrder
      cannot :cancel, CustomerOrder
      can :crud, Category
      can :read, LunchOrder
      can :crud, Menu
    end

    def customer_permissions
      can :read, Product
      can %i[read create cancel], CustomerOrder, user_id: @user.id
      can :read, Category
      cannot :crud, LunchOrder
      can :read, Menu
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  has_many :products

  validates :name, presence: true, length: { minimum: 5 }

  scope :enabled, ->{ where(enabled: :true) }
end

app/models/customer_order.rb
class CustomerOrder < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  validates :user_id, uniqueness: { scope: :menu_id }
end

app/models/customer_order_item.rb
class CustomerOrderItem < ApplicationRecord
  belongs_to :customer_order
end

app/models/lunch_order.rb
class LunchOrder < ApplicationRecord
  has_many :customer_orders, dependent: :destroy
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user, foreign_key: 'created_by'
  has_one_attached :background_img
  def products
    Product.where(id: product_ids)    
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :user, optional: true
  belongs_to :category

  has_many :customer_orders

  validates :name, :description, :price, :quatity, presence: true

  scope :enabled, ->{ where(enabled: :true) }
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  has_many :products
  has_many :menus, foreign_key: 'created_by'
  has_many :customer_orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role_user: [:customer, :restaurant, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied, with: :render_403

  private
  def render_403
    render file: "#{Rails.root}/public/403.html", status: 403, layout: false
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @category.save ? redirect_to(categories_path) : render('new')
  end

  def update
    @category.update(category_params) ? redirect_to(categories_path) : render('edit')
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :enabled)
    end
end 

app/controllers/customer_orders_controller.rb
class CustomerOrdersController < ApplicationController
  load_and_authorize_resource

  def index; end

  def show; end

  def cancel
    if customer_order.update_attribute(:canceled_at, Time.now)
      flash[:notice] = "You canceled order successful!"
      redirect_to(customer_orders_path)
    else 
      flash[:alert] = "You canceled order failure!"
      render('show')
    end
  end

  private
    def customer_order
      @customer_order ||= CustomerOrder.find(params[:id])
    end

    def customer_order_params
      params.require(:customer_order).permit(:user_id, :menu_id, :canceled_at)
    end
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    timenow = Time.current.to_date.strftime('%Y-%m-%d')
    @menu = Menu.by_name(timenow).first
  end
end

app/controllers/lunch_orders_controller.rb
class LunchOrdersController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  load_and_authorize_resource

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @menu.save ? redirect_to(menus_path) : render('new')
  end

  def update
    @menu.update(menu_params) ? redirect_to(menus_path) : render('edit')
  end

  def destroy
    @menu.destroy
    redirect_to menus_path
  end

  private
    def menu_params
      params[:menu][:product_ids]&.reject!(&:blank?)&.map!(&:to_i)
      params.require(:menu).permit(:menu_name, :background_img, :created_by, product_ids: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html { display_products }
      format.csv { export_products }
    end
  end

  def display_products
    @products = @products.order(created_at: :desc)
  end

  def export_products
    send_data(
      Products::ExportCsv.new(display_products).perform,
      type: 'text/csv',
      filename: 'products.csv',
      disposition: 'attachment'
      )
  end

  def new
    @product = Product.new
  end

  def show
    @product
  end

  def edit
    @product
  end

  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))
    redirect_to @product if @product.save
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to products_path if @product.destroy
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :enabled, :quatity, :user_id, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index; end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'updated user successfully!'
      redirect_to @user
    else
      flash[:alert] = 'update user failed!'
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:role_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    'Lunch Service'
  end

  def display_status(status)
    icon_class = status ? 'ok' : 'remove'
    content_tag(:span, nil, class: "glyphicon glyphicon-#{icon_class}")
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
  def category_list
    Category.enabled.pluck(:name, :id)
  end
end

app/helpers/customer_order_helper.rb
module CustomerOrderHelper
  def bill_total(customer_order)
    return 0 unless customer_order.present?
    customer_order.products.sum(&:price)
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def menu_list
    Menu.pluck(:menu_name, :id)
  end

  def display_background_img(menu)
    menu.background_img.attached? ? url_for(menu.background_img) : ''
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def user_can_edit_product
    user_signed_in? && @product.user_id == current_user.id
  end
end

app/views/customer_orders/_table.html.haml
%table.table.table-responsive.table-striped
  %tr
    %th Customer
    %th Date
    %th Canceled at
  - @customer_orders.each do |customer_order|
    %tr
      %td= current_user.email
      %td= customer_order.menu.menu_name
      %td= customer_order.canceled_at
      %td.text-right
        = link_to 'Show', customer_order_path(customer_order), class: 'btn btn-info'
        - if can? :cancel, CustomerOrder
          = link_to 'Cancel', cancel_customer_order_path(customer_order), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/customer_orders/index.html.haml
%h2 Your Orders
%hr
.panel.panel-default
  = render partial: 'table'

app/views/customer_orders/show.html.haml
%p
  %strong Customer:
  = @customer_order.user.email
%p
  %strong Date/Time:
  = @customer_order.lunch_order.order_date
%p
  %strong Product:
  = @customer_order.product.name
%p
  %strong Price:
  = @customer_order.product.price
%p
  %strong Canceled at:
  = @customer_order.canceled_at
= link_to 'Back To Index', customer_orders_path

app/views/menus/_form.html.haml
= simple_form_for @menu, html: { multipart: true} do |f|
  = f.input :menu_name, input_html: { value: Time.current.strftime('%Y-%m-%d') }
  = f.input :product_ids, input_html: { multiple: true, size: Product.enabled.count }, collection: Product.enabled.pluck(:name, :id), selected: f.object.product_ids
  = f.input :created_by, as: :hidden, input_html: { value: current_user.id }
  = f.file_field :background_img
  = f.button :submit, class: 'btn btn-primary'
  = link_to 'Back To Index', menus_path, class: 'btn btn-default'

app/views/menus/_table.html.haml
%table.table.table-responsive.table-striped
  %tr
    %th Date
    %th Products
    %th Created by
    %th
  - @menus.each do |menu|
    %tr
      %td= menu.menu_name
      %td
        - menu.products.each do |product|
          %ul
            %li= product.name
      %td= menu.user.email
      %td.text-right
        - if can? :update, Menu
          = link_to 'Edit', edit_menu_path(menu), class: 'btn btn-primary'
        = link_to 'Show', menu_path(menu), class: 'btn btn-info'
        - if can? :destroy, Menu
          = link_to 'Destroy', menu_path(menu), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/menus/edit.html.haml
.col-md-6.col-md-offset-3
  .edit-book-form
    %h1 Edit Menu
    = render 'form'

app/views/menus/index.html.haml
%h2 Menus
.text-right
  - if can? :create, Menu
    = link_to 'New Menu', new_menu_path , class: 'btn btn-primary'
%hr
.panel.panel-default
  = render partial: 'table'

app/views/menus/new.html.haml
%h1 New Menu
= render 'form'

app/views/menus/show.html.haml
.col-md-8{ style: "background-image:url(#{ display_background_img(@menu) })" }
  .links.btn-group
    = link_to 'Back To Index', menus_path, class: 'btn btn-custom'
    - if can? :update, Menu
      = link_to 'Edit', edit_menu_path(@menu) , class: 'btn btn-custom'
    - if can? :destroy, Menu
      = link_to 'Delete', menu_path(@menu), method: :delete, data: {confirm: 'Are you sure?'} , class: 'btn btn-custom'
  .book-info
    %table.table
      %tr
        %td
          Menu Date: 
        %td
          = @menu.menu_name
      %tr
        %td
          List of Menu: 
      %tr
        %td
          User:
        %td
          = @menu.user.email
      %tr
        %td
          - @menu.products.each do |product|
            %ul
              %li= product.name

app/views/products/_form.html.haml
= simple_form_for @product, html: { multipart: true } do |f|
  = f.input :category_id, collection: category_list, label_method: :first, value_method: :second
  = f.input :name, label: 'Product Name', require: true
  = f.input :description, require: true
  = f.input :price, require: true, input_html: { value: f.object.price || '5000' }
  = f.input :enabled, as: :boolean
  = f.input :quatity, require: true, input_html: { value: f.object.quatity || '1' }
  = f.button :submit

app/views/products/_table.html.haml
%table.table.table-responsive.table-striped
  %tr
    %th Category
    %th Name
    %th Description
    %th Price
    %th Quatity
    %th Enabled
    %th
  - @products.each do |product|
    %tr
      %td= product.category&.name
      %td= product.name
      %td= product.description
      %td= product.price
      %td= product.quatity
      %td= display_status(product.enabled)
      %td.text-right
        - if can? :update, Product
          = link_to 'Edit', edit_product_path(product), class: 'btn btn-primary'
        - if can? :read, Product  
          = link_to 'Show', product_path(product), class: 'btn btn-info'
        - if can? :destroy, Product  
          = link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/products/edit.html.haml
.col-md-6.col-md-offset-3
  .edit-book-form
    %h1 Edit Product
    = render 'form'

app/views/products/index.html.haml
%h2 List of Products
.text-right
  - if can? :create, Product
    = link_to 'New Product', new_product_path, class: 'btn btn-primary'
  = link_to 'Import', product_imports_path, class: 'btn btn-info'
  = link_to 'Export', products_path(format: :csv), class: 'btn btn-info'
%hr
.panel.panel-default
  = render partial: 'table'

app/views/products/new.html.haml
%h1 New Product
= render 'form'
%p
  = link_to 'Back To Index', products_path

app/views/products/show.html.haml
.col-md-8
  .links.btn-group
  - if can? :read, Product
    = link_to 'Back To Index', products_path, class: 'btn btn-custom'
    - if can? :update, Product
      = link_to 'Edit', edit_product_path(@product) , class: 'btn btn-custom'
    - if can? :destroy, Product  
      = link_to 'Delete', product_path(@product), method: :delete, data: {confirm: 'Are you sure?'} , class: 'btn btn-custom'
  .book-info
    %table.table
      %tr
        %td
          Name: 
        %td
          = @product.name
      %tr
        %td
          Description: 
        %td
          = @product.description
      %tr
        %td
          Description: 
        %td
          = @product.price
      %tr
        %td
          Quatity: 
        %td
          = @product.quatity
      %tr
        %td
          Enabled: 
        %td
          = display_status(@product.enabled)