config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  devise_for :users
  resources :categories
  resources :lunch_orders, only: [:index, :show]
  resources :customer_orders do
    resources :customer_order_items
    member do
      post :cancel
    end
  end
  resources :menus
  resources :product_imports do
    collection { post :import }
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud

    @user = user || User.new

    case
    when user.admin?
      can :manage, :all
    when user.restaurant?
      restaurant_permissions
    when user.customer?
      customer_permissions
    else
      cannot :manage, :all
    end
  end

  private
    def restaurant_permissions
      can :crud, Product, user_id: @user.id
      can :read, CustomerOrder
      cannot :cancel, CustomerOrder
      can :crud, Category
      can :read, LunchOrder
      can :crud, Menu
    end

    def customer_permissions
      can :read, Product
      can %i[read create cancel], CustomerOrder, user_id: @user.id
      can :read, Category
      cannot :crud, LunchOrder
      can :read, Menu
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  has_many :products

  validates :name, presence: true, length: { minimum: 5 }

  scope :enabled, ->{ where(enabled: :true) }
end

app/models/customer_order.rb
class CustomerOrder < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  validates :user_id, uniqueness: { scope: :menu_id }
end

app/models/customer_order_item.rb
class CustomerOrderItem < ApplicationRecord
  belongs_to :customer_order
end

app/models/lunch_order.rb
class LunchOrder < ApplicationRecord
  has_many :customer_orders, dependent: :destroy
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user, foreign_key: 'created_by'
  has_one_attached :background_img
  def products
    Product.where(id: product_ids)    
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :user, optional: true
  belongs_to :category

  has_many :customer_orders

  validates :name, :description, :price, :quatity, presence: true

  scope :enabled, ->{ where(enabled: :true) }
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  has_many :products
  has_many :menus, foreign_key: 'created_by'
  has_many :customer_orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role_user: [:customer, :restaurant, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied, with: :render_403

  private
  def render_403
    render file: "#{Rails.root}/public/403.html", status: 403, layout: false
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @category.save ? redirect_to(categories_path) : render('new')
  end

  def update
    @category.update(category_params) ? redirect_to(categories_path) : render('edit')
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :enabled)
    end
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    timenow = Time.current.to_date.strftime('%Y-%m-%d')
    @menu = Menu.by_name(timenow).first
  end
end

app/controllers/lunch_orders_controller.rb
class LunchOrdersController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  load_and_authorize_resource

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @menu.save ? redirect_to(menus_path) : render('new')
  end

  def update
    @menu.update(menu_params) ? redirect_to(menus_path) : render('edit')
  end

  def destroy
    @menu.destroy
    redirect_to menus_path
  end

  private
    def menu_params
      params[:menu][:product_ids]&.reject!(&:blank?)&.map!(&:to_i)
      params.require(:menu).permit(:menu_name, :background_img, :created_by, product_ids: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html { display_products }
      format.csv { export_products }
    end
  end

  def display_products
    @products = @products.order(created_at: :desc)
  end

  def export_products
    send_data(
      Products::ExportCsv.new(display_products).perform,
      type: 'text/csv',
      filename: 'products.csv',
      disposition: 'attachment'
      )
  end

  def new
    @product = Product.new
  end

  def show
    @product
  end

  def edit
    @product
  end

  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))
    redirect_to @product if @product.save
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to products_path if @product.destroy
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :enabled, :quatity, :user_id, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index; end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'updated user successfully!'
      redirect_to @user
    else
      flash[:alert] = 'update user failed!'
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:role_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    'Lunch Service'
  end

  def display_status(status)
    icon_class = status ? 'ok' : 'remove'
    content_tag(:span, nil, class: "glyphicon glyphicon-#{icon_class}")
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
  def category_list
    Category.enabled.pluck(:name, :id)
  end
end

app/helpers/customer_order_helper.rb
module CustomerOrderHelper
  def bill_total(customer_order)
    return 0 unless customer_order.present?
    customer_order.products.sum(&:price)
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def menu_list
    Menu.pluck(:menu_name, :id)
  end

  def display_background_img(menu)
    menu.background_img.attached? ? url_for(menu.background_img) : ''
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def user_can_edit_product
    user_signed_in? && @product.user_id == current_user.id
  end
end

app/views/lunch_orders/index.html.haml
%h2 List of Lunch Orders
%hr
.panel.panel-default
  %table.table.table-responsive.table-striped
    %tr
      %th ID
      %th Order Date
      %th
    - @lunch_orders.each do |lunch_order|
      %tr
        %td= lunch_order.id
        %td= lunch_order.order_date.strftime("%d-%m-%Y")
        %td.text-right
          - if can? :read, LunchOrder
            = link_to 'Show', lunch_order_path(lunch_order), class: 'btn btn-info'

app/views/lunch_orders/show.html.haml
%p
  %strong Order Date:
  = @lunch_order.order_date.strftime("%d-%m-%Y")
= link_to 'Back To Index', lunch_orders_path

app/views/users/edit.html.haml
.col-md-6.col-md-offset-3
  .edit-book-form
    %h1 Edit User
    = simple_form_for @user, html: { multipart: true } do |f|
      = f.input :email, readonly: true
      = f.input :role_user, as: :select, collection: User.role_users.keys.to_a, include_blank: false
      = f.button :submit

app/views/users/index.html.haml
%h2 List of Users
%hr
.panel.panel-default
%table.table.table-responsive.table-striped
  %tr
    %th Email
    %th Role
    %th
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.role_user
      %td.text-right
        - if can? :update, User
          = link_to 'Edit', edit_user_path(user), class: 'btn btn-primary'
        - if can? :read, User
          = link_to 'Show', user_path(user), class: 'btn btn-info'

app/views/users/show.html.haml
.col-md-8
  .links.btn-group
    - if can? :read, User
      = link_to 'Back To Index', users_path, class: 'btn btn-custom'
    - if can? :update, User
      = link_to 'Edit', edit_user_path(@user) , class: 'btn btn-custom'
  .book-info
    %table.table
      %tr
        %td
          Email: 
        %td
          = @user.email
      %tr
        %td
          Role: 
        %td
          = @user.role_user
      %tr
        %td
          Created At: 
        %td
          = @user.created_at
      %tr
        %td
          Updated at: 
        %td
          = @user.updated_at