config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  devise_for :users
  resources :categories
  resources :lunch_orders, only: [:index, :show]
  resources :customer_orders do
    resources :customer_order_items
    member do
      post :cancel
    end
  end
  resources :menus
  resources :product_imports do
    collection { post :import }
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud

    @user = user || User.new

    case
    when user.admin?
      can :manage, :all
    when user.restaurant?
      restaurant_permissions
    when user.customer?
      customer_permissions
    else
      cannot :manage, :all
    end
  end

  private
    def restaurant_permissions
      can :crud, Product, user_id: @user.id
      can :read, CustomerOrder
      cannot :cancel, CustomerOrder
      can :crud, Category
      can :read, LunchOrder
      can :crud, Menu
    end

    def customer_permissions
      can :read, Product
      can %i[read create cancel], CustomerOrder, user_id: @user.id
      can :read, Category
      cannot :crud, LunchOrder
      can :read, Menu
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  has_many :products

  validates :name, presence: true, length: { minimum: 5 }

  scope :enabled, ->{ where(enabled: :true) }
end

app/models/customer_order.rb
class CustomerOrder < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  validates :user_id, uniqueness: { scope: :menu_id }
end

app/models/customer_order_item.rb
class CustomerOrderItem < ApplicationRecord
  belongs_to :customer_order
end

app/models/lunch_order.rb
class LunchOrder < ApplicationRecord
  has_many :customer_orders, dependent: :destroy
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user, foreign_key: 'created_by'
  has_one_attached :background_img
  def products
    Product.where(id: product_ids)    
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :user, optional: true
  belongs_to :category

  has_many :customer_orders

  validates :name, :description, :price, :quatity, presence: true

  scope :enabled, ->{ where(enabled: :true) }
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  has_many :products
  has_many :menus, foreign_key: 'created_by'
  has_many :customer_orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role_user: [:customer, :restaurant, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @category.save ? redirect_to(categories_path) : render('new')
  end

  def update
    @category.update(category_params) ? redirect_to(categories_path) : render('edit')
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :enabled)
    end
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    timenow = Time.current.to_date.strftime('%Y-%m-%d')
    @menu = Menu.by_name(timenow).first
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  load_and_authorize_resource

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @menu.save ? redirect_to(menus_path) : render('new')
  end

  def update
    @menu.update(menu_params) ? redirect_to(menus_path) : render('edit')
  end

  def destroy
    @menu.destroy
    redirect_to menus_path
  end

  private
    def menu_params
      params[:menu][:product_ids]&.reject!(&:blank?)&.map!(&:to_i)
      params.require(:menu).permit(:menu_name, :background_img, :created_by, product_ids: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html { display_products }
      format.csv { export_products }
    end
  end

  def display_products
    @products = @products.order(created_at: :desc)
  end

  def export_products
    send_data(
      Products::ExportCsv.new(display_products).perform,
      type: 'text/csv',
      filename: 'products.csv',
      disposition: 'attachment'
      )
  end

  def new
    @product = Product.new
  end

  def show
    @product
  end

  def edit
    @product
  end

  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))
    redirect_to @product if @product.save
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to products_path if @product.destroy
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :enabled, :quatity, :user_id, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index; end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'updated user successfully!'
      redirect_to @user
    else
      flash[:alert] = 'update user failed!'
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:role_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    'Lunch Service'
  end

  def display_status(status)
    icon_class = status ? 'ok' : 'remove'
    content_tag(:span, nil, class: "glyphicon glyphicon-#{icon_class}")
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
  def category_list
    Category.enabled.pluck(:name, :id)
  end
end

app/helpers/customer_order_helper.rb
module CustomerOrderHelper
  def bill_total(customer_order)
    return 0 unless customer_order.present?
    customer_order.products.sum(&:price)
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def menu_list
    Menu.pluck(:menu_name, :id)
  end

  def display_background_img(menu)
    menu.background_img.attached? ? url_for(menu.background_img) : ''
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def user_can_edit_product
    user_signed_in? && @product.user_id == current_user.id
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title=app_name
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = render partial: 'shared/user_nav'
    - else
      = render partial: 'shared/nav'
    .container
      .row
        = render partial: 'shared/notice'
      - if user_signed_in?
        = yield
      - else
        .row
          .col-sm-6.col-sm-offset-3
            = yield

app/views/shared/_nav.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %h1=app_name
    %ul.nav.navbar-nav.navbar-right
      %li= link_to 'Sign Up', new_user_registration_path
      %li= link_to 'Log In', new_user_session_path

app/views/shared/_notice.html.haml
.col-sm-12
  - if notice.present?
    .alert.alert-success= notice
  - if alert.present?
    .alert.alert-warning= alert

app/views/shared/_user_nav.html.haml
%nav.navbar.navbar-default
  .container
    .row
      .col-sm-12
        .navbar-header
          %h1=app_name
    .row
      .col-sm-12
        %ul.nav.navbar-nav
          %li= link_to 'Home', root_path
          - if can? :read, Category
            %li= link_to 'Categories', categories_path
          - if can? :read, Product
            %li= link_to 'Products', products_path
          - if can? :read, Menu
            %li= link_to 'Menus', menus_path
          - if can? :crud, User
            %li= link_to 'Users', users_path
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to current_user.email, '', class: 'btn btn-secondary dropdown-toggle', aria: { expanded: false, haspopup: true }, data: { toggle: 'dropdown' }
            .dropdown-menu{'aria-labelledby': 'dropdownMenuLink'}
              = link_to 'Menu', menus_path, class: 'dropdown-item'
              %br
              = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
          %li= link_to 'Your Orders', customer_orders_path
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
  .container